### ISSUE TITLE
Testnet branch edition

### ISSUE THREAD

**Issue by raymens** [stellar/docker-stellar-core#31]
Although I don't need it myself, it might lower the barriers for other to run a testnet node.
I know you can connect to testnet from the current docker container, but in the stellar-core repo there's a special branch for testnet.

**Comment by jedmccaleb** [comment]
The testnet branch just represents what we have deployed to testnet. Any of the 3 branches should be able to work with it.

**Comment by raymens** [comment]
If this is the case then this can be ignored :)
